name: ModifyMessage
version: ${project.version}
main: dev.benergy10.modifymessage.ModifyMessage
api-version: 1.13
depend: [ ProtocolLib ]
authors: [ benwoo1110 ]
description: Modify any message sent to players!
